### ISSUE TITLE
Documentation for setting up the app locally

### ISSUE THREAD

**Issue by BrooksPatton** [CodingGarden/live-chat-manager#4]
What API keys do I need to get it running locally? 

Google+ or YouTube API?

Where do I get my Google token?

I'd be happy to write this PR so we can get this running locally for community development.

**Comment by jaaneh** [comment]
You'll need the following in an `.env` file.
```
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_API_KEY=
GOOGLE_TOKEN=
TWITCH_CLIENT_ID=
TWITCH_CLIENT_SECRET=
```

The `GOOGLE_CLIENT_ID`, `GOOGLE_CLIENT_SECRET` you get by registering a Google application  (`Create credentials -> OAuth client ID`) at https://console.developers.google.com/apis/credentials
* The above requires OAuth consent screen to be configured - You'll be prompted for this if this hasn't already beed done. (https://console.developers.google.com/apis/credentials/consent)

The `GOOGLE_API_KEY` you will get by going `Create credentials -> API key` on https://console.developers.google.com/apis/credentials

The `TWITCH_CLIENT_ID` and `TWITCH_CLIENT_SECRET` you get by registering a Twitch application at https://dev.twitch.tv/console/apps

(Not sure what GOOGLE_TOKEN is for, can't find it being used anywhere in the application)

**Comment by w3cj** [comment]
README updated with environment variable description. The old .env.sample was out of date. Only a YouTube API Key and Twitch Client ID are required.
